# Data Cleaning

In [91]:
import pandas as pd
import numpy as np

In [92]:
df = pd.read_csv("../Data/heart_attack_china.csv")

In [93]:
print(df.head(5))

   Patient_ID  Age  Gender Smoking_Status Hypertension Diabetes Obesity  \
0           1   55    Male     Non-Smoker           No       No     Yes
1           2   66  Female         Smoker          Yes       No      No
2           3   69  Female         Smoker           No       No      No
3           4   45  Female         Smoker           No      Yes      No
4           5   39  Female         Smoker           No       No      No

  Cholesterol_Level Air_Pollution_Exposure Physical_Activity  ...  \
0            Normal                   High              High  ...
1               Low                 Medium              High  ...
2               Low                 Medium              High  ...
3            Normal                 Medium               Low  ...
4            Normal                 Medium            Medium  ...

  Hospital_Availability TCM_Use Employment_Status Education_Level  \
0                   Low     Yes        Unemployed         Primary
1                  High      No        Unemployed       Secondary
2                   Low      No        Unemployed         Primary
3                Medium     Yes          Employed         Primary
4                   Low      No           Retired          Higher

  Income_Level Blood_Pressure Chronic_Kidney_Disease Previous_Heart_Attack  \
0          Low            104                    Yes                    No
1       Middle            142                     No                    No
2         High            176                     No                    No
3          Low            178                     No                   Yes
4       Middle            146                    Yes                    No

  CVD_Risk_Score Heart_Attack
0             78           No
1             49           No
2             31           No
3             23           No
4             79           No

[5 rows x 28 columns]

In [94]:
print(df.describe())
print(df.info())
print(df.shape)
print(df.columns)
print(df.dtypes)

          Patient_ID            Age  Blood_Pressure  CVD_Risk_Score
count  239266.000000  239266.000000   239266.000000   239266.000000
mean   119633.500000      59.466284      134.513378       54.485581
std     69070.289091      17.348308       25.991827       25.987743
min         1.000000      30.000000       90.000000       10.000000
25%     59817.250000      44.000000      112.000000       32.000000
50%    119633.500000      59.000000      135.000000       54.000000
75%    179449.750000      75.000000      157.000000       77.000000
max    239266.000000      89.000000      179.000000       99.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239266 entries, 0 to 239265
Data columns (total 28 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Patient_ID              239266 non-null  int64
 1   Age                     239266 non-null  int64
 2   Gender                  239266 non-null  object
 3   Smoking_Status          239266 non-null  object
 4   Hypertension            239266 non-null  object
 5   Diabetes                239266 non-null  object
 6   Obesity                 239266 non-null  object
 7   Cholesterol_Level       239266 non-null  object
 8   Air_Pollution_Exposure  239266 non-null  object
 9   Physical_Activity       239266 non-null  object
 10  Diet_Score              239266 non-null  object
 11  Stress_Level            239266 non-null  object
 12  Alcohol_Consumption     239266 non-null  object
 13  Family_History_CVD      239266 non-null  object
 14  Healthcare_Access       239266 non-null  object
 15  Rural_or_Urban          239266 non-null  object
 16  Region                  239266 non-null  object
 17  Province                239266 non-null  object
 18  Hospital_Availability   239266 non-null  object
 19  TCM_Use                 239266 non-null  object
 20  Employment_Status       239266 non-null  object
 21  Education_Level         179649 non-null  object
 22  Income_Level            239266 non-null  object
 23  Blood_Pressure          239266 non-null  int64
 24  Chronic_Kidney_Disease  239266 non-null  object
 25  Previous_Heart_Attack   239266 non-null  object
 26  CVD_Risk_Score          239266 non-null  int64
 27  Heart_Attack            239266 non-null  object
dtypes: int64(4), object(24)
memory usage: 51.1+ MB
None
(239266, 28)
Index(['Patient_ID', 'Age', 'Gender', 'Smoking_Status', 'Hypertension',
       'Diabetes', 'Obesity', 'Cholesterol_Level', 'Air_Pollution_Exposure',
       'Physical_Activity', 'Diet_Score', 'Stress_Level',
       'Alcohol_Consumption', 'Family_History_CVD', 'Healthcare_Access',
       'Rural_or_Urban', 'Region', 'Province', 'Hospital_Availability',
       'TCM_Use', 'Employment_Status', 'Education_Level', 'Income_Level',
       'Blood_Pressure', 'Chronic_Kidney_Disease', 'Previous_Heart_Attack',
       'CVD_Risk_Score', 'Heart_Attack'],
      dtype='object')
Patient_ID                 int64
Age                        int64
Gender                    object
Smoking_Status            object
Hypertension              object
Diabetes                  object
Obesity                   object
Cholesterol_Level         object
Air_Pollution_Exposure    object
Physical_Activity         object
Diet_Score                object
Stress_Level              object
Alcohol_Consumption       object
Family_History_CVD        object
Healthcare_Access         object
Rural_or_Urban            object
Region                    object
Province                  object
Hospital_Availability     object
TCM_Use                   object
Employment_Status         object
Education_Level           object
Income_Level              object
Blood_Pressure             int64
Chronic_Kidney_Disease    object
Previous_Heart_Attack     object
CVD_Risk_Score             int64
Heart_Attack              object
dtype: object

In [95]:
# Firstly we need to check if there are any missing values in the dataset
print(df.isnull().sum())

Patient_ID                    0
Age                           0
Gender                        0
Smoking_Status                0
Hypertension                  0
Diabetes                      0
Obesity                       0
Cholesterol_Level             0
Air_Pollution_Exposure        0
Physical_Activity             0
Diet_Score                    0
Stress_Level                  0
Alcohol_Consumption           0
Family_History_CVD            0
Healthcare_Access             0
Rural_or_Urban                0
Region                        0
Province                      0
Hospital_Availability         0
TCM_Use                       0
Employment_Status             0
Education_Level           59617
Income_Level                  0
Blood_Pressure                0
Chronic_Kidney_Disease        0
Previous_Heart_Attack         0
CVD_Risk_Score                0
Heart_Attack                  0
dtype: int64

In [96]:
# We have 59617 null values.
print(df['Education_Level'].value_counts())
# Education Level is categorical. Lets set all the null values to a new category called "uknown or none"
df['Education_Level'] = df['Education_Level'].fillna('Unknown or None')

Education_Level
Higher       59942
Primary      59901
Secondary    59806
Name: count, dtype: int64

In [97]:
# Now lets see if we have fixed the missing values
df.isnull().sum()

Patient_ID                0
Age                       0
Gender                    0
Smoking_Status            0
Hypertension              0
Diabetes                  0
Obesity                   0
Cholesterol_Level         0
Air_Pollution_Exposure    0
Physical_Activity         0
Diet_Score                0
Stress_Level              0
Alcohol_Consumption       0
Family_History_CVD        0
Healthcare_Access         0
Rural_or_Urban            0
Region                    0
Province                  0
Hospital_Availability     0
TCM_Use                   0
Employment_Status         0
Education_Level           0
Income_Level              0
Blood_Pressure            0
Chronic_Kidney_Disease    0
Previous_Heart_Attack     0
CVD_Risk_Score            0
Heart_Attack              0
dtype: int64

In [98]:
# Now we can continue the cleaning process by checking for outliers in the dataset
import seaborn as sns
import matplotlib.pyplot as plt

In [99]:
# Function to detect outliers using IQR
def detect_outliers(df):
    outliers = pd.DataFrame(columns=df.columns)
    for col in df.select_dtypes(include=[np.number]).columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        outliers = pd.concat([outliers, df[(df[col] < lower_bound) | (df[col] > upper_bound)]])
    return outliers

# Detect outliers
foundOutliers = detect_outliers(df)
print("Number of outliers detected:", foundOutliers.shape[0])
print(foundOutliers)

Number of outliers detected: 0
Empty DataFrame
Columns: [Patient_ID, Age, Gender, Smoking_Status, Hypertension, Diabetes, Obesity, Cholesterol_Level, Air_Pollution_Exposure, Physical_Activity, Diet_Score, Stress_Level, Alcohol_Consumption, Family_History_CVD, Healthcare_Access, Rural_or_Urban, Region, Province, Hospital_Availability, TCM_Use, Employment_Status, Education_Level, Income_Level, Blood_Pressure, Chronic_Kidney_Disease, Previous_Heart_Attack, CVD_Risk_Score, Heart_Attack]
Index: []

[0 rows x 28 columns]

In [100]:
# We didnt find any outliers in the dataset. Now we can check for duplicates in the dataset.
print("Number of duplicates in the dataset:", df.duplicated().sum())

Number of duplicates in the dataset: 0

In [101]:
print(df.dtypes)
df.head(5)

Patient_ID                 int64
Age                        int64
Gender                    object
Smoking_Status            object
Hypertension              object
Diabetes                  object
Obesity                   object
Cholesterol_Level         object
Air_Pollution_Exposure    object
Physical_Activity         object
Diet_Score                object
Stress_Level              object
Alcohol_Consumption       object
Family_History_CVD        object
Healthcare_Access         object
Rural_or_Urban            object
Region                    object
Province                  object
Hospital_Availability     object
TCM_Use                   object
Employment_Status         object
Education_Level           object
Income_Level              object
Blood_Pressure             int64
Chronic_Kidney_Disease    object
Previous_Heart_Attack     object
CVD_Risk_Score             int64
Heart_Attack              object
dtype: object

,Patient_ID,Age,Gender,Smoking_Status,Hypertension,Diabetes,Obesity,Cholesterol_Level,Air_Pollution_Exposure,Physical_Activity,...,Hospital_Availability,TCM_Use,Employment_Status,Education_Level,Income_Level,Blood_Pressure,Chronic_Kidney_Disease,Previous_Heart_Attack,CVD_Risk_Score,Heart_Attack
0,1,55,Male,Non-Smoker,No,No,Yes,Normal,High,High,...,Low,Yes,Unemployed,Primary,Low,104,Yes,No,78,No
1,2,66,Female,Smoker,Yes,No,No,Low,Medium,High,...,High,No,Unemployed,Secondary,Middle,142,No,No,49,No
2,3,69,Female,Smoker,No,No,No,Low,Medium,High,...,Low,No,Unemployed,Primary,High,176,No,No,31,No
3,4,45,Female,Smoker,No,Yes,No,Normal,Medium,Low,...,Medium,Yes,Employed,Primary,Low,178,No,Yes,23,No
4,5,39,Female,Smoker,No,No,No,Normal,Medium,Medium,...,Low,No,Retired,Higher,Middle,146,Yes,No,79,No

In [102]:
cat_featues = ['Gender', 'Smoking_Status', 'Cholesterol_Level',
                        'Air_Pollution_Exposure', 'Physical_Activity', 
                       'Diet_Score', 'Stress_Level', 'Healthcare_Access',
                       'Rural_or_Urban', 'Region', 'Province', 'Hospital_Availability',
                       'Employment_Status', 'Education_Level',
                       'Income_Level', 'Hypertension', 'Diabetes',
                       'Obesity', 'Alcohol_Consumption', 'Family_History_CVD',
                       'TCM_Use', 'Chronic_Kidney_Disease', 
                        'Previous_Heart_Attack', 'Heart_Attack']
df_modeling = pd.get_dummies(df, columns=cat_featues, drop_first=True, dtype=int)
df_modeling.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239266 entries, 0 to 239265
Data columns (total 48 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Patient_ID                       239266 non-null  int64
 1   Age                              239266 non-null  int64
 2   Blood_Pressure                   239266 non-null  int64
 3   CVD_Risk_Score                   239266 non-null  int64
 4   Gender_Male                      239266 non-null  int64
 5   Smoking_Status_Smoker            239266 non-null  int64
 6   Cholesterol_Level_Low            239266 non-null  int64
 7   Cholesterol_Level_Normal         239266 non-null  int64
 8   Air_Pollution_Exposure_Low       239266 non-null  int64
 9   Air_Pollution_Exposure_Medium    239266 non-null  int64
 10  Physical_Activity_Low            239266 non-null  int64
 11  Physical_Activity_Medium         239266 non-null  int64
 12  Diet_Score_Moderate              239266 non-null  int64
 13  Diet_Score_Poor                  239266 non-null  int64
 14  Stress_Level_Low                 239266 non-null  int64
 15  Stress_Level_Medium              239266 non-null  int64
 16  Healthcare_Access_Moderate       239266 non-null  int64
 17  Healthcare_Access_Poor           239266 non-null  int64
 18  Rural_or_Urban_Urban             239266 non-null  int64
 19  Region_Eastern                   239266 non-null  int64
 20  Region_Northern                  239266 non-null  int64
 21  Region_Southern                  239266 non-null  int64
 22  Region_Western                   239266 non-null  int64
 23  Province_Gansu                   239266 non-null  int64
 24  Province_Guangdong               239266 non-null  int64
 25  Province_Henan                   239266 non-null  int64
 26  Province_Qinghai                 239266 non-null  int64
 27  Province_Shandong                239266 non-null  int64
 28  Province_Shanghai                239266 non-null  int64
 29  Province_Sichuan                 239266 non-null  int64
 30  Hospital_Availability_Low        239266 non-null  int64
 31  Hospital_Availability_Medium     239266 non-null  int64
 32  Employment_Status_Retired        239266 non-null  int64
 33  Employment_Status_Unemployed     239266 non-null  int64
 34  Education_Level_Primary          239266 non-null  int64
 35  Education_Level_Secondary        239266 non-null  int64
 36  Education_Level_Unknown or None  239266 non-null  int64
 37  Income_Level_Low                 239266 non-null  int64
 38  Income_Level_Middle              239266 non-null  int64
 39  Hypertension_Yes                 239266 non-null  int64
 40  Diabetes_Yes                     239266 non-null  int64
 41  Obesity_Yes                      239266 non-null  int64
 42  Alcohol_Consumption_Yes          239266 non-null  int64
 43  Family_History_CVD_Yes           239266 non-null  int64
 44  TCM_Use_Yes                      239266 non-null  int64
 45  Chronic_Kidney_Disease_Yes       239266 non-null  int64
 46  Previous_Heart_Attack_Yes        239266 non-null  int64
 47  Heart_Attack_Yes                 239266 non-null  int64
dtypes: int64(48)
memory usage: 87.6 MB

In [104]:
# Now we can save the cleaned dataset to a pickle file
import pickle

data = df_modeling
print(data.head(5))
with open('../Data/cleanedDF.pkl', 'wb') as f:
    pickle.dump(data, f)

   Patient_ID  Age  Blood_Pressure  CVD_Risk_Score  Gender_Male  \
0           1   55             104              78            1
1           2   66             142              49            0
2           3   69             176              31            0
3           4   45             178              23            0
4           5   39             146              79            0

   Smoking_Status_Smoker  Cholesterol_Level_Low  Cholesterol_Level_Normal  \
0                      0                      0                         1
1                      1                      1                         0
2                      1                      1                         0
3                      1                      0                         1
4                      1                      0                         1

   Air_Pollution_Exposure_Low  Air_Pollution_Exposure_Medium  ...  \
0                           0                              0  ...
1                           0                              1  ...
2                           0                              1  ...
3                           0                              1  ...
4                           0                              1  ...

   Income_Level_Middle  Hypertension_Yes  Diabetes_Yes  Obesity_Yes  \
0                    0                 0             0            1
1                    1                 1             0            0
2                    0                 0             0            0
3                    0                 0             1            0
4                    1                 0             0            0

   Alcohol_Consumption_Yes  Family_History_CVD_Yes  TCM_Use_Yes  \
0                        1                       0            1
1                        0                       1            0
2                        0                       0            0
3                        1                       0            1
4                        0                       0            0

   Chronic_Kidney_Disease_Yes  Previous_Heart_Attack_Yes  Heart_Attack_Yes
0                           1                          0                 0
1                           0                          0                 0
2                           0                          0                 0
3                           0                          1                 0
4                           1                          0                 0

[5 rows x 48 columns]